### ISSUE TITLE
Ajout de son non fonctionnel

### ISSUE THREAD

**Issue by boscorelly** [edgardmessias/browsernotification#20]
Bonjour,

j'ai créé un répertoire sounds.
J'ai mis _son_.ogg/mp3 dedans.

Mais le son n'apparait pas dans la liste des sons utilisables...

Une idée ?

**Comment by edgardmessias** [comment]
Send me full path, please.

**Comment by boscorelly** [comment]
c:\xampp\htdocs\glpi\plugins\browsernotification\sounds\attention-seeker.ogg/mp3

**Comment by edgardmessias** [comment]
Move to c:\xampp\htdocs\glpi\sounds\attention-seeker.ogg/mp3

Em 13 de set de 2017 9:52 AM, "Camille Ollié" <notifications@github.com>
escreveu:

**Comment by boscorelly** [comment]
Perfect, it works =)
