### ISSUE TITLE
[1.1.9] Browser notification doesn't work in Google Chrome 64

### ISSUE THREAD

**Issue by eremetter** [edgardmessias/browsernotification#25]
Hello,
browser notification doesn't work in Google Chrome 64.0.3282.119

**Comment by edgardmessias** [comment]
Try switch to HTTPS.

Is a restriction in Google Chrome for HTTP.

Em 28 de jan de 2018 12:50 PM, "eremetter" <notifications@github.com>
escreveu:

**Comment by eremetter** [comment]
It's good. It works with https for Chrome 64. Thanks.
