### ISSUE TITLE
Dúvida: Acesso aos usuários comuns

### ISSUE THREAD

**Issue by MsPatronum** [edgardmessias/browsernotification#29]
Boa tarde.

Uso o GLPI como ferramenta de abertura de chamados onde trabalho.
Gostaria de me informar acerca do Plug-in e se usuários básicos tem acesso às configurações, podendo assim ativar e desativar as notificações ou se tudo é feito por usuários Administradores, valendo como regra para todos os usuários.

Obrigada.

**Comment by edgardmessias** [comment]
Boa tarde.

Primeiro: Você precisa que o GLPI esteja em **HTTPS** para funcionar para qualquer usuário (Restrição das versões mais recentes do Chrome)
Segundo: A partir do GLPI 9.3, foi integrado esse tipo de notificação no GLPI, sendo que só os administradores conseguem personalizar
Terceiro: Com essa extensão, cada usuário pode definir o que receber, dentro das opções definidas, mas o administrador pode definir quais serão as notificações padrões, caso o usuário não altere
